todo

---
chkrootkit
sed /etc/chkrootkit.config
RUN_DAILY="true"
RUN_DAILY_OPTS="-q"
DIFF_MODE="true"
---

---
apt-get install --no-install-recommends checksecurity

/etc/checksecurity.conf

#CHECKSECURITY_EMAIL="root"
---


= Evaulating files for implantetion.
:icons: font




=== add resporitorys 

----
apt install -y logwatch libpam-pwquality unattended-upgrades haveged openntpd lynx sslscan sysstat openssl-blacklist openssl-blacklist-extra
----
# Create /var/log/sulog.
touch /var/log/sulog
chown root:root /var/log/sulog
chmod 0640 /var/log/sulog

# Create the sudo log directory tree.
mkdir /var/log/sudo-io

# Set some file ownerships.
chown root:root /etc/at.allow
chown root:root /etc/cron.allow
chown root:root /etc/sudoers
chown -R root:root /var/spool/cron
chown root:syslog /var/log/sudo-io

# Set some file permissions.
chmod 0400 /etc/at.allow
chmod 0400 /etc/cron.allow
chmod 0400 /etc/crontab
chmod 0700 /etc/skel/.ssh
chmod 0600 /etc/skel/.ssh/authorized_keys
chmod 0440 /etc/sudoers
chmod 0700 /var/log/sudo-io

# Enable some system services.  `systemctl list-unit-files` is your friend.
systemctl enable acpid
systemctl enable sysstat

# Disable other system services.
systemctl disable iscsi
systemctl disable iscsid
systemctl disable mountnfs-bootclean
systemctl disable mountnfs
systemctl disable umountnfs

# Hand^wScript hack the /etc/postfix/main.cf file because it was completely
# rewritten when the Debian configurator asked you some questions.
----
echo "smtpd_tls_ciphers = high" >> /etc/postfix/main.cf
echo "smtpd_tls_exclude_ciphers = aNULL, MD5, DES, 3DES, DES-CBC3-SHA, RC4-SHA, AES256-SHA, AES128-SHA" >> /etc/postfix/main.cf
echo "smtp_tls_protocols = !SSLv2, !SSLv3" >> /etc/postfix/main.cf
echo "smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3" >> /etc/postfix/main.cf
echo "smtp_tls_note_starttls_offer = yes" >> /etc/postfix/main.cf
echo "smtpd_tls_received_header = yes" >> /etc/postfix/main.cf
echo "" >> /etc/postfix/main.cf
----

# Ensure that the Apache mod_headers and mod_rewrite modules are enabled so
# that, if apache2 is installed and enabled, it won't scream and die.
----
ln -s /etc/apache2/mods-available/headers.load \
    /etc/apache2/mods-enabled/headers.load
ln -s /etc/apache2/mods-available/rewrite.load \
    /etc/apache2/mods-enabled/rewrite.load
----
